kind: Pod
apiVersion: v1
metadata:
  name: web-pvc
spec:
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: pvc-web

  containers:
    - name: nginx
      image: nginx:1.14
      ports:
      - containerPort: 80
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
