kind: Deployment
apiVersion: apps/v1
metadata:
  name: dep-mainui
  annotations: 
    kubernetes.io/change-cause: version 2.4
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      name: apache
      app: main
  template:
    metadata: 
      name: httpd-pod
      labels:
        name: apache
        app: main
        rel: stable
    spec:
      containers:
      - name: httpd-container
        image: httpd:2.4
        ports:
          - containerPort: 80
