kind: Pod
apiVersion: v1
metadata:
  labels:
    app: project
  name: tensorflow-pod
spec:
  containers:
  - name: tensorflow
    image: tensorflow/tensorflow:nightly-jupyter
    ports:
    - containerPort: 8888
      protocol: TCP
  nodeSelector:
    disktype: sdd
    gpu: "true"